version: '3'

services:
      
  docker-webapp:
    image: rafaelelias/springwebflux:0.0.1
    networks:
      - spring_net
    ports:
      - "8080:8080"
  
networks:
  spring_net:
    driver: bridge
    