version: '3'

services:
  
  docker-webapp:
    image: rafaelelias/springmvc:0.0.1
    ports:
      - "8080:8080"
    networks:
      - spring_net
      
networks:
  spring_net:
    driver: bridge